server {
  listen 80;
  server_name _;

  resolver 127.0.0.11 valid=10s ipv6=off;

  # KIOSK (accessible LAN)
  location /kiosk/ {
    set $kiosk_upstream http://kiosk:80;
    rewrite ^/kiosk/(.*)$ /$1 break;
    proxy_pass $kiosk_upstream;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  # ADMIN (IP VPN du comité)
  location /admin/ {
    allow 172.16.0.111;
    deny all;

    set $admin_upstream http://admin:80;
    rewrite ^/admin/(.*)$ /$1 break;
    proxy_pass $admin_upstream;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  # API KIOSK (IP Kiosk)
  location /api/kiosk/ {
    allow 172.20.0.4;
    allow 172.16.0.111;
    allow 172.19.0.9;
    deny all;

    # Backend runs directly on the host machine during local operation.
    set $backend_upstream http://172.17.0.7:3000;
    proxy_pass $backend_upstream;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  # API ADMIN (IP VPN du comité)
  location /api/admin/ {
    allow 172.16.0.111;
    deny all;

    # Backend runs directly on the host machine during local operation.
    set $backend_upstream http://172.17.0.7:3000;
    proxy_pass $backend_upstream;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location = / {
    return 302 /kiosk/;
  }
}
